apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enterprise-analyst

resources:
  - 00-namespace.yaml
  - 01-secret.yaml
  - 02-configmap.yaml
  - 03-mysql.yaml
  - 04-chromadb.yaml
  - 05-backend.yaml
